const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const d=$("#desktop"),wins=$("#wins"),icons=$("#icons"),ed=$("#editor");let z=5,n=0,ic=0;
const E=s=>(s||"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[m]));function toast(t){let x=$("#toast");x.textContent=t;x.classList.add("show");setTimeout(()=>x.classList.remove("show"),1500)}
function select(x){$$(".selected").forEach(e=>e.classList.remove("selected"));x.classList.add("selected");edit(x)}
function drag(x,h=x){h.onpointerdown=e=>{if(e.target.closest(".close"))return;select(x);x.style.zIndex=++z;let r=x.getBoundingClientRect(),q=d.getBoundingClientRect(),ox=e.clientX-r.left,oy=e.clientY-r.top;function mv(v){let X=Math.max(0,Math.min(v.clientX-q.left-ox,q.width-r.width)),Y=Math.max(0,Math.min(v.clientY-q.top-oy,q.height-r.height-42));x.style.left=X/q.width*100+"%";x.style.top=Y/q.height*100+"%"}function up(){removeEventListener("pointermove",mv);removeEventListener("pointerup",up)}addEventListener("pointermove",mv);addEventListener("pointerup",up)}}
const defs={note:["memo.txt","오늘 해야 할 일\n• 잊지 않기\n• 일찍 돌아가기"],message:["MESSENGER","상대 | 아직 안 자?\n나 | 응. 왜?\n상대 | 그냥."],music:["NOW PLAYING","Song Title | Artist"],photo:["PHOTO VIEWER",""],browser:["BROWSER","dearly://home | 오늘의 검색 기록"],folder:["SECRET","photo.jpg\nmemo.txt\ndo_not_delete.txt"]};
function addWin(t){let w=document.createElement("div");w.className="window "+t;w.dataset.type=t;w.dataset.title=defs[t][0];w.dataset.text=defs[t][1];w.style.left=18+(++n*4)%35+"%";w.style.top=12+(n*5)%30+"%";w.style.zIndex=++z;w.innerHTML=`<div class="bar"><i class="dot"></i><span></span><button class="close">×</button></div><div class="content"></div>`;wins.append(w);render(w);drag(w,w.querySelector(".bar"));w.onpointerdown=()=>{w.style.zIndex=++z;select(w)};w.querySelector(".close").onclick=e=>{e.stopPropagation();w.remove()};select(w)}
function render(w){let c=w.querySelector(".content"),t=w.dataset.type,s=w.dataset.text||"";w.querySelector(".bar span").textContent=w.dataset.title;if(t==="note")c.textContent=s;if(t==="message")c.innerHTML='<div class="messages">'+s.split("\n").filter(Boolean).map(l=>{let a=l.split("|"),me=a[0].trim()==="나";return `<div class="bubble ${me?"me":""}"><b>${E(a[0].trim())}</b><br>${E(a.slice(1).join("|").trim())}</div>`}).join("")+"</div>";if(t==="music"){let a=s.split("|");c.innerHTML=`<div class="musicgrid"><div class="cover">♫</div><div><b>${E(a[0])}</b><br><small>${E(a[1])}</small></div></div>`}if(t==="photo")c.innerHTML=`<div class="photo" ${w.dataset.img?`style="background-image:url('${w.dataset.img}')"`:""}>${w.dataset.img?"":"PHOTO"}</div>`;if(t==="browser"){let a=s.split("|");c.innerHTML=`<small>◁　▷　↻　${E(a[0])}</small><hr><b>${E(a[1])}</b><p>가상의 브라우저 화면입니다.</p>`}if(t==="folder")c.innerHTML=`<div class="folder">${s.split("\n").filter(Boolean).map(v=>`<div class="file">${E(v)}</div>`).join("")}</div>`}
function edit(x){if(x.classList.contains("icon")){ed.innerHTML=`<h3>DESKTOP ICON</h3><label>이름<input id="en" value="${E(x.dataset.name)}"></label><button id="del">삭제</button>`;$("#en").oninput=e=>{x.dataset.name=e.target.value;x.querySelector("span").textContent=e.target.value};$("#del").onclick=()=>x.remove();return}let t=x.dataset.type;ed.innerHTML=`<h3>${t.toUpperCase()}</h3><label>창 제목<input id="et" value="${E(x.dataset.title)}"></label><label style="display:block">내용<textarea id="ex" rows="6">${E(x.dataset.text)}</textarea></label>${t==="photo"?'<label style="display:block">사진<input id="ep" type="file" accept="image/*"></label>':""}${t==="message"?'<p>메신저는 “이름 | 내용”을 한 줄씩 입력해. “나 | 내용”은 오른쪽 말풍선으로 표시돼.</p>':""}`;$("#et").oninput=e=>{x.dataset.title=e.target.value;render(x)};$("#ex").oninput=e=>{x.dataset.text=e.target.value;render(x)};if(t==="photo")$("#ep").onchange=e=>{let f=e.target.files[0];if(!f)return,r=new FileReader;r.onload=()=>{x.dataset.img=r.result;render(x)};r.readAsDataURL(f)}}
function addIcon(name){let x=document.createElement("div");x.className="icon";x.dataset.name=name;x.style.left=(ic%4)*82+"px";x.style.top=Math.floor(ic/4)*72+"px";ic++;x.innerHTML=`<div class="ico"></div><span>${E(name)}</span>`;icons.append(x);drag(x);x.onclick=()=>select(x)}
$$("[data-add]").forEach(b=>b.onclick=()=>addWin(b.dataset.add));$("#addIcon").onclick=()=>{addIcon($("#iconName").value||"new folder");$("#iconName").value=""};$("#theme").onchange=e=>d.className="desktop "+e.target.value;$("#bg").oninput=e=>d.style.backgroundColor=e.target.value;$("#accent").oninput=e=>d.style.setProperty("--a",e.target.value);$("#clock").oninput=e=>$("#tray").textContent=e.target.value;$("#wall").onchange=e=>{let f=e.target.files[0];if(!f)return;$("#filename").textContent=f.name;let r=new FileReader;r.onload=()=>d.style.backgroundImage=`url("${r.result}")`;r.readAsDataURL(f)};
$("#ooc").onclick=async()=>{let p=`[OOC: 지금까지의 대화와 설정을 바탕으로 {{char}}의 개인 PC에 있을 법한 내용을 작성해주세요. 기존 설정과 {{char}}·{{user}}의 관계성을 우선하고 중요한 설정을 임의로 확정하지 마세요.\n\n1. 바탕화면 폴더 6개\n2. 파일 이름 6개\n3. 메모장 내용\n4. 최근 재생 음악 3곡\n5. {{user}}와의 메신저 대화 6줄\n6. 최근 검색어 5개\n7. 비밀 폴더와 내부 파일 4개\n8. 휴지통 파일 3개\n9. 화면에서 가장 눈에 띄는 한 가지\n\n캐릭터의 성격, 말투, 직업, 습관과 현재 관계가 자연스럽게 드러나게 작성해주세요.]`;try{await navigator.clipboard.writeText(p);toast("OOC가 복사됐어 ♡")}catch{let a=document.createElement("textarea");a.value=p;document.body.append(a);a.select();document.execCommand("copy");a.remove();toast("OOC가 복사됐어 ♡")}};
$("#save").onclick=async()=>{if(!window.html2canvas)return toast("저장 라이브러리를 불러오지 못했어.");$$(".selected").forEach(x=>x.classList.remove("selected"));try{await document.fonts.ready;let c=await html2canvas(d,{scale:2,useCORS:true,backgroundColor:null});let a=document.createElement("a");a.download="DEARLY_DESKTOP.png";a.href=c.toDataURL("image/png");a.click();toast("PNG 저장 완료 ♡")}catch(e){console.error(e);toast("PNG 저장 중 문제가 생겼어.")}};
addIcon("photos");addIcon("secret");addWin("note");addWin("music");